import Head from 'next/head';
import Portfolio from '../components/Sections/Portfolio';
import WeHelp from '../components/Sections/WeHelp';
import SmartShop from '../components/Sections/SmartShop';
import SpecialEX from '../components/Sections/SpecialEX';
import ContactUs from '../components/Sections/ContactUs';
import Carousel from '../components/Sections/Carousel';
import HomeStart from '../components/Sections/HomeStart';
import Testimonials from '../components/Sections/Testimonials';

export default function Home() {
  return (
    <div>
      <Head>
        <title>ChickFarm</title>
        <meta name="description" content="Generated by C" />
        <link rel="icon" href="/" />
      </Head>

      <div>
        <HomeStart />
        {/* <Carousel /> */}
        {/* <SpecialEX /> */}
        <WeHelp />
        {/* <SmartShop /> */}
        {/* <Portfolio /> */}
        {/* <Testimonials /> */}
        {/* <ContactUs /> */}
      </div>
    </div>
  );
}
